# Change these first
owner: lei-splashtop # Your GitHub organization or username, where this repository lives
repo: sep-uptime # The name of this repository

sites:
  - name: SplashVault-dev
    url: https://dev.pwm.splashshield.ai/#!/
  - name: SDP-dev
    url: https://dev-spd-cluster.splashshield.ai/login
  - name: Grafana-dev
    url: https://loki.dev.splashshield.ai/
  - name: SplashVault-stage
    url: https://vault.stage.splashshield.ai/
  - name: SDP-stage
    url: https://gate.stage.splashshield.ai/
  - name: Grafana-stage
    url: https://devops.controller1-us-west-2.stage.splashshield.ai/grafana/
  - name: Assets
    url: http://splashlock-assets.splashshield.ai/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /sep-uptime
  logoUrl: https://dev-spd-cluster.splashshield.ai/static/media/logo.89a87b57.svg
  name: Sep-Uptime
  introTitle: "Sep-uptime monitor sep website status"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
